### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by AaronLayton** [callmecavs/jump.js#6] opened 2015-11-30 09:46 UTC
Just had a quick check of this with the Timeline tool and I get the below

![2015-11-30_09h46_09](https://cloud.githubusercontent.com/assets/694964/11468420/3bee5f24-9747-11e5-88ab-40e612e4df7d.png)

**Comment by callmecavs** [comment] 2015-11-30 15:52
would you mind digging into this a bit further for me? I think the spike may be caused by `requestAnimationFrame` being called 60 times per second, to achieve a 60fps scroll. The scroll completing would explain the "cliff". In that case, I wouldn't think it's a memory leak. I know the Chrome dev tools allow you to dig into the JS stack and see what function(s) are being called, perhaps your tools provide a similar feature?

will leave this open until I hear back, thank you

**Comment by AaronLayton** [comment] 2015-11-30 16:01
It could be as you say - I just went to your test site... hit record, pressed the go down button, pressed to go up button.

I havn't had chance to dig into it yet though, could it be creating variables every time rAF calls?

**Comment by callmecavs** [comment] 2015-11-30 16:12
the `_loop` function is what runs within each `requestAnimationFrame` call. that code is highlighted here: https://github.com/callmecavs/jump.js/blob/master/src/jump.js#L18-L31

it's only referencing and working with existing class properties - all that is created is more `requestAnimationFrame`s. therefore, I don't think this is related to creating variables. there is some math related to the easing function that happens in each loop, but I couldn't imagine those low level operations would cause this type of spike.

if you get a chance, i'd really appreciate you doing some more digging :raised_hands:

**Comment by callmecavs** [comment] 2015-11-30 16:28
![pasted image at 2015_11_30 11_22 am](https://cloud.githubusercontent.com/assets/2293641/11477277/3bddc34a-9755-11e5-9a0f-499388d6659d.png)

did some profiling in the Chrome dev tools, and I'm not seeing anything out of the ordinary. going to close this for now, as I believe what you're seeing is related to the `requestAnimationFrame` calls. if in your futher testing you come across something in particular, I'll reopen it and take a peak. thanks again for your efforts

**Closed as completed by callmecavs** 2015-11-30 16:28 UTC

**Comment by callmecavs** [comment] 2015-11-30 16:30
here are some screenshots of the heap from the Chrome devtools as well:

![pasted image at 2015_11_30 11_29 am](https://cloud.githubusercontent.com/assets/2293641/11477396/c7cbe198-9755-11e5-9979-e476e134cd03.png)

![pasted image at 2015_11_30 11_30 am](https://cloud.githubusercontent.com/assets/2293641/11477440/f7e89d30-9755-11e5-8909-860e4b86a1c3.png)

seems as though everything from the lib is insignificantly small

**Comment by callmecavs** [comment] 2015-11-30 16:32
looping in @jaxgeller, as he helped with some of this profiling
